#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr across
#' @importFrom dplyr all_of
#' @importFrom dplyr bind_rows
#' @importFrom dplyr filter
#' @importFrom dplyr if_else
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom ggplot2 %+replace%
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 alpha
#' @importFrom ggplot2 annotate
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_blank
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rect
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 rel
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_size_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 sec_axis
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 waiver
#' @importFrom ggrepel geom_text_repel
#' @importFrom grDevices colorRampPalette
#' @importFrom highcharter datetime_to_timestamp
#' @importFrom highcharter hc_add_series
#' @importFrom highcharter hc_add_theme
#' @importFrom highcharter hc_exporting
#' @importFrom highcharter hc_legend
#' @importFrom highcharter hc_theme
#' @importFrom highcharter hc_tooltip
#' @importFrom highcharter hc_xAxis
#' @importFrom highcharter hc_yAxis
#' @importFrom highcharter hcaes
#' @importFrom highcharter highchart
#' @importFrom htmlwidgets JS
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @importFrom rlang sym
#' @importFrom stats setNames
#' @importFrom svglite svglite
#' @importFrom sysfonts font_add
#' @importFrom tidyr pivot_longer
## usethis namespace: end
NULL
